FROM node:16.13.0 as base

WORKDIR /app

ENV VUE_APP_ENV=production

COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npm run build

FROM nginx:stable-alpine as final

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=base /app/dist /usr/share/nginx/html

EXPOSE 8080