version: "3"
services:
  frontend:
    build: ./frontend
    image: frontend-blueprint-guest-mode-only
    ports:
      - "8080:8080"
    container_name: "frontend-blueprint-guest-mode-only"
    restart: unless-stopped